<?php

/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

//* Template Name: Front Page


//add_filter( 'genesis_pre_get_option_site_layout', '__genesis_return_full_width_content' );

genesis();



// Remove 'site-inner' from structural wrap
/*add_theme_support( 'genesis-structural-wraps', array( 'header', 'footer-widgets', 'footer' ) );

/**
 * Add the attributes from 'entry', since this replaces the main entry
 *
 * @param array $attributes Existing attributes.
 * @return array Amended attributes.
 */
/*function be_site_inner_attr( $attributes ) {
	
	// Add a class of 'full' for styling this .site-inner differently
	$attributes['class'] .= ' full';
	
	// Add the attributes from .entry, since this replaces the main entry
	$attributes = wp_parse_args( $attributes, genesis_attributes_entry( array() ) );
	
	return $attributes;
}
add_filter( 'genesis_attr_site-inner', 'be_site_inner_attr' );


// Build the page
get_header();
do_action( 'be_content_area' );
the_post();
the_content();
get_footer();
*/
